name: venv
channels:
  - pyg
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - abseil-cpp=20211102.0
  - absl-py=1.4.0
  - aiohttp=3.9.0
  - aiosignal=1.2.0
  - alembic=1.13.3
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=14.0.2
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=23.1.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.10.55
  - babel=2.11.0
  - beautifulsoup4=4.12.2
  - black=24.4.2
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.6.2
  - boost-cpp=1.82.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - cachetools=4.2.2
  - certifi=2025.4.26
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - colorama=0.4.6
  - colorlog=5.0.1
  - comm=0.1.2
  - contourpy=1.2.0
  - cpuonly=2.0
  - cryptography=41.0.7
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - et_xmlfile=1.1.0
  - executing=0.8.3
  - filelock=3.13.1
  - fonttools=4.51.0
  - freetype=2.12.1
  - frozenlist=1.4.0
  - gflags=2.2.2
  - giflib=5.2.1
  - glog=0.5.0
  - gmpy2=2.1.2
  - google-auth=2.22.0
  - google-auth-oauthlib=0.4.1
  - greenlet=3.1.1
  - grpc-cpp=1.48.2
  - grpcio=1.48.2
  - gtest=1.14.0
  - icc_rt=2022.1.0
  - icu=73.1
  - idna=3.4
  - intel-openmp=2023.1.0
  - ipykernel=6.25.0
  - ipython=8.20.0
  - ipywidgets=8.0.4
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter=1.0.0
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.5.0
  - jupyter_events=0.8.0
  - jupyter_server=2.10.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.8
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - jupyterlab_widgets=3.0.9
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lerc=3.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcurl=8.7.1
  - libdeflate=1.17
  - libevent=2.1.12
  - libffi=3.4.4
  - libjpeg-turbo=2.0.0
  - libpng=1.6.39
  - libpq=12.15
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libssh2=1.11.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libuv=1.44.2
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - lightgbm=4.6.0
  - lz4-c=1.9.4
  - mako=1.2.3
  - markdown=3.4.1
  - markupsafe=2.1.3
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - monotonicnetworks=1.5.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpir=3.0.0
  - mpmath=1.3.0
  - multidict=6.0.4
  - mypy_extensions=1.0.0
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - nest-asyncio=1.5.6
  - networkx=3.1
  - notebook=7.0.6
  - notebook-shim=0.2.3
  - numexpr=2.8.7
  - numpy=1.26.3
  - numpy-base=1.26.3
  - oauthlib=3.2.2
  - openjpeg=2.4.0
  - openpyxl=3.1.5
  - openssl=3.4.1
  - optuna=4.2.1
  - orc=1.7.4
  - overrides=7.4.0
  - packaging=23.1
  - pandas=2.1.4
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pathspec=0.10.3
  - pillow=10.0.1
  - pip=23.3.1
  - platformdirs=3.10.0
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - protobuf=3.20.3
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pyarrow=14.0.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pyg=2.4.0
  - pygments=2.15.1
  - pyjwt=2.4.0
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.11.7
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - pytorch=2.1.2
  - pytorch-mutex=1.0
  - pytz=2023.3.post1
  - pywin32=305
  - pywinpty=2.0.10
  - pyyaml=6.0.1
  - pyzmq=25.1.0
  - qt-main=5.15.2
  - qtconsole=5.5.0
  - qtpy=2.4.1
  - re2=2022.04.01
  - referencing=0.30.2
  - requests=2.31.0
  - requests-oauthlib=1.3.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - rsa=4.7.2
  - scikit-learn=1.2.2
  - scipy=1.11.4
  - seaborn=0.12.2
  - send2trash=1.8.2
  - setuptools=68.2.2
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.2.0
  - soupsieve=2.5
  - sqlalchemy=2.0.37
  - sqlite=3.41.2
  - stack_data=0.2.0
  - sympy=1.12
  - tbb=2021.8.0
  - tensorboard=2.6.0
  - tensorboard-plugin-wit=1.6.0
  - tensorboardx=2.2
  - terminado=0.17.1
  - threadpoolctl=2.2.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - torchaudio=2.1.2
  - torchinfo=1.8.0
  - torchvision=0.16.2
  - tornado=6.3.3
  - tqdm=4.65.0
  - traitlets=5.7.1
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023d
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - urllib3=1.26.18
  - utf8proc=2.6.1
  - vc=14.2
  - vc14_runtime=14.42.34438
  - vs2015_runtime=14.42.34438
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - werkzeug=2.2.3
  - wheel=0.41.2
  - widgetsnbextension=4.0.5
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xz=5.4.5
  - yaml=0.2.5
  - yarl=1.9.3
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - torch-cluster==1.6.3+pt21cpu
prefix: C:\.conda\envs\venv
